const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Clerk',
  description: 'Set up Clerk authentication with middleware and auth pages',
  supportedFrameworks: ['nextjs'],

  steps(context) {
    const { usesAppRouter, usesSrcDir } = context;
    const appDir = usesSrcDir ? 'src/app' : 'app';
    const middlewarePath = usesSrcDir ? 'src/middleware.js' : 'middleware.js';

    const middleware = `import { clerkMiddleware, createRouteMatcher } from '@clerk/nextjs/server';

const isPublicRoute = createRouteMatcher([
  '/',
  '/sign-in(.*)',
  '/sign-up(.*)',
]);

export default clerkMiddleware(async (auth, request) => {
  if (!isPublicRoute(request)) {
    await auth.protect();
  }
});

export const config = {
  matcher: [
    '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
    '/(api|trpc)(.*)',
  ],
};
`;

    const signInPage = `import { SignIn } from '@clerk/nextjs';

export default function SignInPage() {
  return (
    <div className="flex min-h-screen items-center justify-center">
      <SignIn />
    </div>
  );
}
`;

    const signUpPage = `import { SignUp } from '@clerk/nextjs';

export default function SignUpPage() {
  return (
    <div className="flex min-h-screen items-center justify-center">
      <SignUp />
    </div>
  );
}
`;

    const layoutExample = `// app/layout.clerk-example.js
// Reference: wrap your root layout with ClerkProvider
// Copy the relevant parts into your app/layout.js

import { ClerkProvider } from '@clerk/nextjs';

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
`;

    return [
      {
        type: 'exec',
        label: 'Install @clerk/nextjs',
        command: 'npm install @clerk/nextjs',
        cwd: context.projectDir,
      },
      {
        type: 'write',
        label: `Write ${middlewarePath}`,
        filePath: middlewarePath,
        content: middleware,
      },
      {
        type: 'write',
        label: `Write ${appDir}/(auth)/sign-in/[[...sign-in]]/page.js`,
        filePath: `${appDir}/(auth)/sign-in/[[...sign-in]]/page.js`,
        content: signInPage,
      },
      {
        type: 'write',
        label: `Write ${appDir}/(auth)/sign-up/[[...sign-up]]/page.js`,
        filePath: `${appDir}/(auth)/sign-up/[[...sign-up]]/page.js`,
        content: signUpPage,
      },
      {
        type: 'write',
        label: 'Write app/layout.clerk-example.js (reference)',
        filePath: `${appDir}/layout.clerk-example.js`,
        content: layoutExample,
      },
      {
        type: 'env',
        label: 'Add Clerk env vars to .env.example',
        vars: {
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'pk_test_your-publishable-key',
          CLERK_SECRET_KEY: 'sk_test_your-secret-key',
          NEXT_PUBLIC_CLERK_SIGN_IN_URL: '/sign-in',
          NEXT_PUBLIC_CLERK_SIGN_UP_URL: '/sign-up',
          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: '/dashboard',
          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: '/dashboard',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/clerk.md',
        content: docContent(DATE, appDir),
      },
    ];
  },

  nextSteps() {
    return [
      'Create a Clerk application at https://clerk.com',
      'Copy your Publishable Key and Secret Key into .env.local',
      'Wrap your root layout with <ClerkProvider> (see app/layout.clerk-example.js)',
      'Routes not in isPublicRoute() will now require authentication',
      'Use auth() in Server Components and useUser() in Client Components',
    ];
  },
};

function docContent(date, appDir) {
  return `# Clerk Setup Guide
> Generated by ai-scaffold on ${date}

## What is Clerk?
Clerk is a complete user authentication and management platform. It provides pre-built UI components, session management, and user profiles.

## What was set up
| Item | Detail |
|------|--------|
| Package | \`@clerk/nextjs\` |
| \`middleware.js\` | Route protection via clerkMiddleware |
| \`${appDir}/(auth)/sign-in/\` | Sign-in page using Clerk's \`<SignIn />\` |
| \`${appDir}/(auth)/sign-up/\` | Sign-up page using Clerk's \`<SignUp />\` |
| \`${appDir}/layout.clerk-example.js\` | Reference layout with ClerkProvider |

## Environment Variables
| Variable | Description | Where to get it |
|----------|-------------|-----------------|
| \`NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY\` | Public key for Clerk | Clerk dashboard → API Keys |
| \`CLERK_SECRET_KEY\` | Secret key (server only) | Clerk dashboard → API Keys |
| \`NEXT_PUBLIC_CLERK_SIGN_IN_URL\` | Path to sign-in page | \`/sign-in\` |
| \`NEXT_PUBLIC_CLERK_SIGN_UP_URL\` | Path to sign-up page | \`/sign-up\` |
| \`NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL\` | Redirect after sign-in | \`/dashboard\` |
| \`NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL\` | Redirect after sign-up | \`/dashboard\` |

## Usage

### Step 1: Wrap Layout with ClerkProvider
Edit \`${appDir}/layout.js\`:
\`\`\`jsx
import { ClerkProvider } from '@clerk/nextjs';

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
\`\`\`

### Server Components
\`\`\`js
import { auth, currentUser } from '@clerk/nextjs/server';

// Protect a route
export default async function Dashboard() {
  const { userId } = await auth();
  if (!userId) redirect('/sign-in');

  const user = await currentUser();
  return <div>Hello, {user.firstName}!</div>;
}
\`\`\`

### Client Components
\`\`\`jsx
'use client';
import { useUser, useAuth, UserButton, SignInButton } from '@clerk/nextjs';

export function Header() {
  const { isSignedIn, user } = useUser();

  return (
    <header>
      {isSignedIn ? (
        <>
          <span>Hello, {user.firstName}</span>
          <UserButton afterSignOutUrl="/" />
        </>
      ) : (
        <SignInButton />
      )}
    </header>
  );
}
\`\`\`

### Protecting API Routes
\`\`\`js
import { auth } from '@clerk/nextjs/server';
import { NextResponse } from 'next/server';

export async function GET() {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  return NextResponse.json({ userId });
}
\`\`\`

## Production Checklist
- [ ] Create a Clerk application at https://clerk.com
- [ ] Set NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY and CLERK_SECRET_KEY in your hosting env
- [ ] Configure allowed origins in Clerk dashboard
- [ ] Set up webhooks for user creation/deletion events
- [ ] Review and customize the sign-in/sign-up appearance

## Troubleshooting
- **"ClerkProvider not found"**: Ensure you've wrapped your root layout with \`<ClerkProvider>\`
- **Redirect loops**: Check that sign-in/sign-up URLs in env vars match your actual routes
- **Middleware not running**: Verify the matcher in \`middleware.js\` covers your routes

## Resources
- [Clerk Docs](https://clerk.com/docs)
- [Next.js Quickstart](https://clerk.com/docs/quickstarts/nextjs)
- [Protecting Routes](https://clerk.com/docs/references/nextjs/clerk-middleware)
- [Webhooks](https://clerk.com/docs/integrations/webhooks)
`;
}
