import { installStep, installDevStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'CockroachDB',
  description: 'Set up CockroachDB Serverless — distributed, resilient Postgres-compatible SQL database',
  category: 'Database — SQL (Managed Cloud)',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    // CockroachDB uses the postgres wire protocol; pg driver works fine
    const dbFile = hasTypescript
      ? `import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from './schema';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL!,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
});

export const db = drizzle(pool, { schema });
`
      : `import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from './schema.js';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
});

export const db = drizzle(pool, { schema });
`;

    const schemaFile = hasTypescript
      ? `import { pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`
      : `import { pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`;

    const drizzleConfig = hasTypescript
      ? `import type { Config } from 'drizzle-kit';

export default {
  schema: './lib/schema.ts',
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
} satisfies Config;
`
      : `/** @type { import("drizzle-kit").Config } */
export default {
  schema: './lib/schema.js',
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
};
`;

    return [
      installStep(packageManager, ['pg', 'drizzle-orm']),
      installDevStep(packageManager, ['drizzle-kit', '@types/pg'], 'Install drizzle-kit, @types/pg (dev)'),
      {
        type: 'write',
        label: `Write lib/db.${ext}`,
        filePath: `lib/db.${ext}`,
        content: dbFile,
      },
      {
        type: 'write',
        label: `Write lib/schema.${ext}`,
        filePath: `lib/schema.${ext}`,
        content: schemaFile,
      },
      {
        type: 'write',
        label: `Write drizzle.config.${ext}`,
        filePath: `drizzle.config.${ext}`,
        content: drizzleConfig,
      },
      {
        type: 'env',
        label: 'Add DATABASE_URL to .env.example',
        vars: {
          DATABASE_URL: 'postgresql://user:password@your-cluster.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/cockroachdb.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Create a free serverless cluster at https://cockroachlabs.cloud',
      'Go to your cluster → Connect → Connection string and copy the URL',
      'Copy DATABASE_URL into .env',
      'Push your schema: `npx drizzle-kit push`',
      'Import { db } from "@/lib/db" to query your database',
    ];
  },
};

function docContent(date) {
  return `# CockroachDB Setup Guide
> Generated by ai-scaffold on ${date}

## What is CockroachDB?
CockroachDB is a distributed SQL database that is Postgres-compatible, globally scalable, and resilient to node failures. The Serverless tier offers a generous free tier with no ops required.

## What was set up
| Item | Detail |
|------|--------|
| Packages | \`pg\`, \`drizzle-orm\` |
| Dev packages | \`drizzle-kit\`, \`@types/pg\` |
| \`lib/db.js\` | Drizzle + node-postgres client (Postgres-compatible) |
| \`lib/schema.js\` | Example users table |
| \`drizzle.config.js\` | Drizzle Kit configuration |

## Environment Variables
| Variable | Description | Where to get it |
|----------|-------------|-----------------|
| \`DATABASE_URL\` | CockroachDB connection string | Cluster → Connect → Connection string |

## Usage

### Querying (Postgres-compatible)
\`\`\`js
import { db } from '@/lib/db';
import { users } from '@/lib/schema';
import { eq } from 'drizzle-orm';

const allUsers = await db.select().from(users);
await db.insert(users).values({ name: 'Alice', email: 'alice@example.com' });
await db.update(users).set({ name: 'Bob' }).where(eq(users.id, 1));
await db.delete(users).where(eq(users.id, 1));
\`\`\`

### Schema Management
\`\`\`bash
npx drizzle-kit push
npx drizzle-kit studio
\`\`\`

## Production Checklist
- [ ] Create cluster at https://cockroachlabs.cloud (free serverless tier available)
- [ ] Enable SSL (already configured in lib/db.js for production)
- [ ] Set DATABASE_URL in your hosting environment
- [ ] Enable automatic backups in the CockroachDB Cloud Console
- [ ] Review multi-region options if you need low-latency globally

## Resources
- [CockroachDB Docs](https://www.cockroachlabs.com/docs)
- [CockroachDB Cloud](https://cockroachlabs.cloud)
- [Drizzle + CockroachDB](https://orm.drizzle.team/docs/get-started-postgresql)
`;
}
