import { installStep, installDevStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Drizzle ORM',
  description: 'Set up Drizzle ORM standalone — choose your SQL dialect (postgres/mysql/sqlite)',
  category: 'ORM / Database Tools',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const schemaPostgres = `import { pgTable, serial, text, timestamp, boolean, integer } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const posts = pgTable('posts', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  content: text('content'),
  published: boolean('published').default(false).notNull(),
  authorId: integer('author_id').references(() => users.id),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`;

    const dbPostgres = hasTypescript
      ? `import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from './schema';

const pool = new Pool({ connectionString: process.env.DATABASE_URL! });
export const db = drizzle(pool, { schema });
`
      : `import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from './schema.js';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
export const db = drizzle(pool, { schema });
`;

    const drizzleConfig = hasTypescript
      ? `import type { Config } from 'drizzle-kit';

export default {
  schema: './lib/schema.ts',
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: { url: process.env.DATABASE_URL! },
} satisfies Config;
`
      : `/** @type { import("drizzle-kit").Config } */
export default {
  schema: './lib/schema.js',
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: { url: process.env.DATABASE_URL },
};
`;

    const seedFile = hasTypescript
      ? `import { db } from './lib/db';
import { users } from './lib/schema';

async function seed() {
  console.log('Seeding...');
  await db.insert(users).values([
    { name: 'Alice', email: 'alice@example.com' },
    { name: 'Bob', email: 'bob@example.com' },
  ]).onConflictDoNothing();
  console.log('Done.');
  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
`
      : `import { db } from './lib/db.js';
import { users } from './lib/schema.js';

async function seed() {
  console.log('Seeding...');
  await db.insert(users).values([
    { name: 'Alice', email: 'alice@example.com' },
    { name: 'Bob', email: 'bob@example.com' },
  ]).onConflictDoNothing();
  console.log('Done.');
  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
`;

    return [
      installStep(packageManager, ['drizzle-orm', 'pg']),
      installDevStep(packageManager, ['drizzle-kit', '@types/pg'], 'Install drizzle-kit, @types/pg (dev)'),
      {
        type: 'write',
        label: `Write lib/schema.${ext}`,
        filePath: `lib/schema.${ext}`,
        content: schemaPostgres,
      },
      {
        type: 'write',
        label: `Write lib/db.${ext}`,
        filePath: `lib/db.${ext}`,
        content: dbPostgres,
      },
      {
        type: 'write',
        label: `Write drizzle.config.${ext}`,
        filePath: `drizzle.config.${ext}`,
        content: drizzleConfig,
      },
      {
        type: 'write',
        label: `Write seed.${ext}`,
        filePath: `seed.${ext}`,
        content: seedFile,
      },
      {
        type: 'env',
        label: 'Add DATABASE_URL to .env.example',
        vars: {
          DATABASE_URL: 'postgresql://user:password@localhost:5432/myapp',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/drizzle.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Set DATABASE_URL in .env',
      'Push schema: `npx drizzle-kit push`',
      'Open Drizzle Studio: `npx drizzle-kit studio`',
      'Run seed: `node seed.js`',
      'For MySQL, swap to drizzle-orm/mysql2 and update drizzle.config dialect',
      'For SQLite, swap to drizzle-orm/better-sqlite3 and update drizzle.config dialect',
    ];
  },
};

function docContent(date) {
  return `# Drizzle ORM Setup Guide
> Generated by ai-scaffold on ${date}

## What was set up
| Item | Detail |
|------|--------|
| Packages | \`drizzle-orm\`, \`pg\` |
| Dev packages | \`drizzle-kit\`, \`@types/pg\` |
| \`lib/schema.js\` | Users + Posts tables (PostgreSQL dialect) |
| \`lib/db.js\` | Drizzle client with connection pool |
| \`drizzle.config.js\` | Drizzle Kit configuration |
| \`seed.js\` | Database seed script |

## Usage

### Querying
\`\`\`js
import { db } from '@/lib/db';
import { users, posts } from '@/lib/schema';
import { eq, and, desc, like } from 'drizzle-orm';

// Select
const allUsers = await db.select().from(users);
const user = await db.select().from(users).where(eq(users.id, 1));

// Insert
const [newUser] = await db.insert(users).values({ name: 'Alice', email: 'alice@example.com' }).returning();

// Update
await db.update(users).set({ name: 'Bob' }).where(eq(users.id, 1));

// Delete
await db.delete(users).where(eq(users.id, 1));

// Join
const usersWithPosts = await db
  .select()
  .from(users)
  .leftJoin(posts, eq(posts.authorId, users.id));

// Filter + sort + limit
const recent = await db.select().from(posts)
  .where(eq(posts.published, true))
  .orderBy(desc(posts.createdAt))
  .limit(10);
\`\`\`

### Migrations
\`\`\`bash
npx drizzle-kit push       # push schema (no migration files)
npx drizzle-kit generate   # generate SQL migration files
npx drizzle-kit migrate    # apply migration files
npx drizzle-kit studio     # open visual DB browser
\`\`\`

## Switching Dialects

### MySQL
\`\`\`js
import { drizzle } from 'drizzle-orm/mysql2';
import mysql from 'mysql2/promise';
const pool = mysql.createPool({ uri: process.env.DATABASE_URL });
export const db = drizzle(pool, { schema, mode: 'default' });
\`\`\`

### SQLite
\`\`\`js
import { drizzle } from 'drizzle-orm/better-sqlite3';
import Database from 'better-sqlite3';
const sqlite = new Database('local.db');
export const db = drizzle(sqlite, { schema });
\`\`\`

## Resources
- [Drizzle ORM Docs](https://orm.drizzle.team)
- [Drizzle Kit Docs](https://orm.drizzle.team/kit-docs/overview)
`;
}
