import { installStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'MongoDB',
  description: 'Set up MongoDB with Mongoose ODM — Atlas cloud or local Docker',
  category: 'Database — NoSQL',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const dockerCompose = `version: '3.8'

services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: myapp
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
`;

    const dbFile = hasTypescript
      ? `import mongoose from 'mongoose';

let isConnected = false;

export async function connectDB(): Promise<void> {
  if (isConnected) return;

  const uri = process.env.MONGODB_URI;
  if (!uri) throw new Error('MONGODB_URI environment variable is not set');

  await mongoose.connect(uri);
  isConnected = true;
  console.log('MongoDB connected');
}

export { mongoose };
`
      : `import mongoose from 'mongoose';

let isConnected = false;

export async function connectDB() {
  if (isConnected) return;

  const uri = process.env.MONGODB_URI;
  if (!uri) throw new Error('MONGODB_URI environment variable is not set');

  await mongoose.connect(uri);
  isConnected = true;
  console.log('MongoDB connected');
}

export { mongoose };
`;

    const userModel = hasTypescript
      ? `import { Schema, model, models, Document } from 'mongoose';

export interface IUser extends Document {
  name: string;
  email: string;
  createdAt: Date;
}

const UserSchema = new Schema<IUser>(
  {
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
  },
  { timestamps: true }
);

export const User = models.User || model<IUser>('User', UserSchema);
`
      : `import { Schema, model, models } from 'mongoose';

const UserSchema = new Schema(
  {
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
  },
  { timestamps: true }
);

export const User = models.User || model('User', UserSchema);
`;

    return [
      installStep(packageManager, ['mongoose']),
      {
        type: 'write',
        label: 'Write docker-compose.mongodb.yml',
        filePath: 'docker-compose.mongodb.yml',
        content: dockerCompose,
      },
      {
        type: 'write',
        label: `Write lib/db.${ext}`,
        filePath: `lib/db.${ext}`,
        content: dbFile,
      },
      {
        type: 'write',
        label: `Write lib/models/user.${ext}`,
        filePath: `lib/models/user.${ext}`,
        content: userModel,
      },
      {
        type: 'env',
        label: 'Add MONGODB_URI to .env.example',
        vars: {
          MONGODB_URI: 'mongodb://root:rootpassword@localhost:27017/myapp?authSource=admin',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/mongodb.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Start local MongoDB: `docker compose -f docker-compose.mongodb.yml up -d`',
      'Or create a free Atlas cluster at https://mongodb.com/atlas',
      'Copy your connection string into MONGODB_URI in .env',
      'Call connectDB() at app startup (or before each query in serverless)',
      'Import models from lib/models/ and query with Mongoose',
    ];
  },
};

function docContent(date) {
  return `# MongoDB Setup Guide
> Generated by ai-scaffold on ${date}

## What was set up
| Item | Detail |
|------|--------|
| Package | \`mongoose\` |
| \`docker-compose.mongodb.yml\` | Local MongoDB 7 container |
| \`lib/db.js\` | Singleton connection helper with caching |
| \`lib/models/user.js\` | Example User model with timestamps |

## Environment Variables
| Variable | Description | Where to get it |
|----------|-------------|-----------------|
| \`MONGODB_URI\` | MongoDB connection string | MongoDB Atlas dashboard or local Docker |

## Usage

### Connect to the database
\`\`\`js
import { connectDB } from '@/lib/db';

// Call once at app startup, or before each API handler in serverless
await connectDB();
\`\`\`

### Using models
\`\`\`js
import { connectDB } from '@/lib/db';
import { User } from '@/lib/models/user';

await connectDB();

// Find all users
const users = await User.find();

// Find one
const user = await User.findOne({ email: 'alice@example.com' });

// Create
const newUser = await User.create({ name: 'Alice', email: 'alice@example.com' });

// Update
await User.findByIdAndUpdate(id, { name: 'Bob' });

// Delete
await User.findByIdAndDelete(id);
\`\`\`

### Defining a new model
\`\`\`js
import { Schema, model, models } from 'mongoose';

const PostSchema = new Schema({
  title: { type: String, required: true },
  content: String,
  author: { type: Schema.Types.ObjectId, ref: 'User' },
}, { timestamps: true });

export const Post = models.Post || model('Post', PostSchema);
\`\`\`

## Atlas Setup
1. Create a free cluster at https://mongodb.com/atlas
2. Go to Database → Connect → Connect your application
3. Copy the connection string into \`MONGODB_URI\`
4. Replace \`<password>\` with your database user password

## Production Checklist
- [ ] Use MongoDB Atlas for production (free tier available)
- [ ] Enable Atlas IP Access List (restrict to your server IPs)
- [ ] Set MONGODB_URI in your hosting environment
- [ ] Enable Atlas backups
- [ ] Create database indexes for frequently queried fields

## Docker Commands
\`\`\`bash
# Start
docker compose -f docker-compose.mongodb.yml up -d

# Stop
docker compose -f docker-compose.mongodb.yml down

# Connect with mongosh
docker exec -it <container-name> mongosh -u root -p rootpassword
\`\`\`

## Resources
- [Mongoose Docs](https://mongoosejs.com/docs)
- [MongoDB Atlas](https://www.mongodb.com/atlas)
- [MongoDB Node.js Driver](https://www.mongodb.com/docs/drivers/node)
`;
}
