import { installStep, installDevStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'MySQL (Local Docker)',
  description: 'Set up a local MySQL 8 database via Docker with mysql2 + Drizzle ORM',
  category: 'Database — SQL (Local)',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const dockerCompose = `version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
`;

    const dbFile = hasTypescript
      ? `import { drizzle } from 'drizzle-orm/mysql2';
import mysql from 'mysql2/promise';
import * as schema from './schema';

const pool = mysql.createPool({
  uri: process.env.DATABASE_URL!,
});

export const db = drizzle(pool, { schema, mode: 'default' });
`
      : `import { drizzle } from 'drizzle-orm/mysql2';
import mysql from 'mysql2/promise';
import * as schema from './schema.js';

const pool = mysql.createPool({
  uri: process.env.DATABASE_URL,
});

export const db = drizzle(pool, { schema, mode: 'default' });
`;

    const schemaFile = `import { mysqlTable, int, varchar, timestamp } from 'drizzle-orm/mysql-core';

export const users = mysqlTable('users', {
  id: int('id').primaryKey().autoincrement(),
  name: varchar('name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`;

    const drizzleConfig = hasTypescript
      ? `import type { Config } from 'drizzle-kit';

export default {
  schema: './lib/schema.ts',
  out: './drizzle',
  dialect: 'mysql',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
} satisfies Config;
`
      : `/** @type { import("drizzle-kit").Config } */
export default {
  schema: './lib/schema.js',
  out: './drizzle',
  dialect: 'mysql',
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
};
`;

    return [
      installStep(packageManager, ['mysql2', 'drizzle-orm']),
      installDevStep(packageManager, ['drizzle-kit'], 'Install drizzle-kit (dev)'),
      {
        type: 'write',
        label: 'Write docker-compose.mysql.yml',
        filePath: 'docker-compose.mysql.yml',
        content: dockerCompose,
      },
      {
        type: 'write',
        label: `Write lib/db.${ext}`,
        filePath: `lib/db.${ext}`,
        content: dbFile,
      },
      {
        type: 'write',
        label: `Write lib/schema.${ext}`,
        filePath: `lib/schema.${ext}`,
        content: schemaFile,
      },
      {
        type: 'write',
        label: `Write drizzle.config.${ext}`,
        filePath: `drizzle.config.${ext}`,
        content: drizzleConfig,
      },
      {
        type: 'env',
        label: 'Add DATABASE_URL to .env.example',
        vars: {
          DATABASE_URL: 'mysql://myapp:myapp_password@localhost:3306/myapp',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/mysql.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Start MySQL: `docker compose -f docker-compose.mysql.yml up -d`',
      'Copy .env.example to .env and verify DATABASE_URL',
      'Push your schema: `npx drizzle-kit push`',
      'Open Drizzle Studio: `npx drizzle-kit studio`',
      'Import { db } from "@/lib/db" to query your database',
    ];
  },
};

function docContent(date) {
  return `# MySQL Setup Guide
> Generated by ai-scaffold on ${date}

## What was set up
| Item | Detail |
|------|--------|
| Packages | \`mysql2\`, \`drizzle-orm\` |
| Dev packages | \`drizzle-kit\` |
| \`docker-compose.mysql.yml\` | Local MySQL 8 container |
| \`lib/db.js\` | Drizzle client using mysql2 pool |
| \`lib/schema.js\` | Example users table |
| \`drizzle.config.js\` | Drizzle Kit configuration |

## Environment Variables
| Variable | Description |
|----------|-------------|
| \`DATABASE_URL\` | MySQL connection string |

## Usage

### Start local database
\`\`\`bash
docker compose -f docker-compose.mysql.yml up -d
\`\`\`

### Querying with Drizzle
\`\`\`js
import { db } from '@/lib/db';
import { users } from '@/lib/schema';
import { eq } from 'drizzle-orm';

const allUsers = await db.select().from(users);
await db.insert(users).values({ name: 'Alice', email: 'alice@example.com' });
await db.update(users).set({ name: 'Bob' }).where(eq(users.id, 1));
await db.delete(users).where(eq(users.id, 1));
\`\`\`

### Schema Management
\`\`\`bash
npx drizzle-kit push
npx drizzle-kit generate
npx drizzle-kit migrate
npx drizzle-kit studio
\`\`\`

## Production Checklist
- [ ] Use a managed provider (PlanetScale, Railway, AWS RDS, Aiven)
- [ ] Set DATABASE_URL in your hosting environment
- [ ] Enable SSL connections
- [ ] Set up automated backups
- [ ] Change all default passwords before deploying

## Resources
- [Drizzle ORM MySQL Docs](https://orm.drizzle.team/docs/get-started-mysql)
- [mysql2 Docs](https://github.com/sidorares/node-mysql2)
- [MySQL Docker Image](https://hub.docker.com/_/mysql)
`;
}
