const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Neon',
  description: 'Set up Neon serverless Postgres with Drizzle ORM',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const dbFile = hasTypescript
      ? `import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import * as schema from './schema';

const sql = neon(process.env.DATABASE_URL!);
export const db = drizzle(sql, { schema });
`
      : `import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import * as schema from './schema.js';

const sql = neon(process.env.DATABASE_URL);
export const db = drizzle(sql, { schema });
`;

    const schemaFile = hasTypescript
      ? `import { pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`
      : `import { pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`;

    const drizzleConfig = hasTypescript
      ? `import type { Config } from 'drizzle-kit';

export default {
  schema: './lib/schema.ts',
  out: './drizzle',
  driver: 'pg',
  dbCredentials: {
    connectionString: process.env.DATABASE_URL!,
  },
} satisfies Config;
`
      : `/** @type { import("drizzle-kit").Config } */
export default {
  schema: './lib/schema.js',
  out: './drizzle',
  driver: 'pg',
  dbCredentials: {
    connectionString: process.env.DATABASE_URL,
  },
};
`;

    return [
      {
        type: 'exec',
        label: 'Install @neondatabase/serverless and drizzle-orm',
        command: 'npm install @neondatabase/serverless drizzle-orm',
        cwd: context.projectDir,
      },
      {
        type: 'exec',
        label: 'Install drizzle-kit (dev)',
        command: 'npm install --save-dev drizzle-kit',
        cwd: context.projectDir,
      },
      {
        type: 'write',
        label: `Write lib/db.${ext}`,
        filePath: `lib/db.${ext}`,
        content: dbFile,
      },
      {
        type: 'write',
        label: `Write lib/schema.${ext}`,
        filePath: `lib/schema.${ext}`,
        content: schemaFile,
      },
      {
        type: 'write',
        label: `Write drizzle.config.${ext}`,
        filePath: `drizzle.config.${ext}`,
        content: drizzleConfig,
      },
      {
        type: 'env',
        label: 'Add DATABASE_URL to .env.example',
        vars: {
          DATABASE_URL: 'postgresql://user:password@ep-xxx.us-east-1.aws.neon.tech/neondb?sslmode=require',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/neon.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Create a Neon project at https://neon.tech',
      'Copy your connection string into .env (rename .env.example to .env)',
      'Run `npx drizzle-kit push` to push your schema to Neon',
      'Run `npx drizzle-kit studio` to open Drizzle Studio (visual DB browser)',
      'Import { db } from "@/lib/db" and query with Drizzle ORM',
    ];
  },
};

function docContent(date) {
  return `# Neon Setup Guide
> Generated by ai-scaffold on ${date}

## What is Neon?
Neon is a serverless Postgres platform with branching, autoscaling, and a generous free tier. It works great with edge runtimes (Vercel Edge, Cloudflare Workers).

## What was set up
| Item | Detail |
|------|--------|
| Package | \`@neondatabase/serverless\` + \`drizzle-orm\` |
| Dev package | \`drizzle-kit\` |
| \`lib/db.js\` | Drizzle client connected to Neon |
| \`lib/schema.js\` | Example users table schema |
| \`drizzle.config.js\` | Drizzle Kit configuration |

## Environment Variables
| Variable | Description | Where to get it |
|----------|-------------|-----------------|
| \`DATABASE_URL\` | Neon connection string | Neon dashboard → Connection Details |

## Usage

### Querying
\`\`\`js
import { db } from '@/lib/db';
import { users } from '@/lib/schema';
import { eq } from 'drizzle-orm';

// Select all
const allUsers = await db.select().from(users);

// Select by condition
const user = await db.select().from(users).where(eq(users.email, 'user@example.com'));

// Insert
await db.insert(users).values({ name: 'Alice', email: 'alice@example.com' });

// Update
await db.update(users).set({ name: 'Bob' }).where(eq(users.id, 1));

// Delete
await db.delete(users).where(eq(users.id, 1));
\`\`\`

### Adding Tables to Schema
\`\`\`js
import { pgTable, serial, text, integer, boolean } from 'drizzle-orm/pg-core';

export const posts = pgTable('posts', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  userId: integer('user_id').references(() => users.id),
  published: boolean('published').default(false),
});
\`\`\`

## Local Development
\`\`\`bash
# Push schema changes to Neon
npx drizzle-kit push

# Generate SQL migration files
npx drizzle-kit generate

# Apply migrations
npx drizzle-kit migrate

# Open visual DB browser
npx drizzle-kit studio
\`\`\`

## Production Checklist
- [ ] Create a Neon project at https://neon.tech
- [ ] Set DATABASE_URL in your hosting environment
- [ ] Run \`npx drizzle-kit push\` or \`migrate\` in your CI/CD pipeline
- [ ] Consider using Neon branching for preview environments

## Troubleshooting
- **Connection timeout**: Neon uses connection pooling; use the pooled connection string for serverless
- **SSL errors**: Ensure \`?sslmode=require\` is appended to your connection string
- **Schema drift**: Run \`npx drizzle-kit push\` to sync your schema with the DB

## Resources
- [Neon Docs](https://neon.tech/docs)
- [Drizzle ORM Docs](https://orm.drizzle.team)
- [Drizzle + Neon Guide](https://orm.drizzle.team/docs/get-started-postgresql#neon)
`;
}
