const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'OAuth',
  description: 'Set up Auth.js v5 (next-auth@beta) with GitHub and Google providers',
  supportedFrameworks: ['nextjs'],

  steps(context) {
    const { usesSrcDir } = context;
    const appDir = usesSrcDir ? 'src/app' : 'app';

    const authConfig = `import NextAuth from 'next-auth';
import GitHub from 'next-auth/providers/github';
import Google from 'next-auth/providers/google';

export const { handlers, auth, signIn, signOut } = NextAuth({
  providers: [
    GitHub({
      clientId: process.env.AUTH_GITHUB_ID,
      clientSecret: process.env.AUTH_GITHUB_SECRET,
    }),
    Google({
      clientId: process.env.AUTH_GOOGLE_ID,
      clientSecret: process.env.AUTH_GOOGLE_SECRET,
    }),
  ],
  callbacks: {
    authorized({ auth, request: { nextUrl } }) {
      const isLoggedIn = !!auth?.user;
      const isOnProtected = nextUrl.pathname.startsWith('/dashboard');
      if (isOnProtected) {
        if (isLoggedIn) return true;
        return false; // Redirect to login
      }
      return true;
    },
  },
});
`;

    const routeHandler = `import { handlers } from '@/auth';
export const { GET, POST } = handlers;
`;

    const authHelpers = `import { auth } from '@/auth';
import { redirect } from 'next/navigation';

/**
 * Require authentication in a Server Component or API route.
 * Redirects to /api/auth/signin if not authenticated.
 */
export async function requireAuth() {
  const session = await auth();
  if (!session?.user) {
    redirect('/api/auth/signin');
  }
  return session;
}

/**
 * Get the current session (returns null if not authenticated).
 */
export async function getSession() {
  return auth();
}
`;

    const layoutExample = `// ${appDir}/layout.oauth-example.js
// Reference: wrap your root layout with SessionProvider for client-side session access
// Copy the relevant parts into your ${appDir}/layout.js

import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
`;

    return [
      {
        type: 'exec',
        label: 'Install next-auth@beta',
        command: 'npm install next-auth@beta',
        cwd: context.projectDir,
      },
      {
        type: 'write',
        label: 'Write auth.js',
        filePath: 'auth.js',
        content: authConfig,
      },
      {
        type: 'write',
        label: `Write ${appDir}/api/auth/[...nextauth]/route.js`,
        filePath: `${appDir}/api/auth/[...nextauth]/route.js`,
        content: routeHandler,
      },
      {
        type: 'write',
        label: 'Write lib/auth-helpers.js',
        filePath: 'lib/auth-helpers.js',
        content: authHelpers,
      },
      {
        type: 'write',
        label: `Write ${appDir}/layout.oauth-example.js (reference)`,
        filePath: `${appDir}/layout.oauth-example.js`,
        content: layoutExample,
      },
      {
        type: 'env',
        label: 'Add OAuth env vars to .env.example',
        vars: {
          AUTH_SECRET: 'generate-with-openssl-rand-base64-32',
          AUTH_GITHUB_ID: 'your-github-oauth-app-client-id',
          AUTH_GITHUB_SECRET: 'your-github-oauth-app-client-secret',
          AUTH_GOOGLE_ID: 'your-google-oauth-client-id',
          AUTH_GOOGLE_SECRET: 'your-google-oauth-client-secret',
          NEXTAUTH_URL: 'http://localhost:3000',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/oauth.md',
        content: docContent(DATE, appDir),
      },
    ];
  },

  nextSteps() {
    return [
      'Generate AUTH_SECRET: run `openssl rand -base64 32`',
      'Create a GitHub OAuth App at https://github.com/settings/applications/new',
      '  - Set callback URL to: http://localhost:3000/api/auth/callback/github',
      'Create a Google OAuth client at https://console.cloud.google.com',
      '  - Set callback URL to: http://localhost:3000/api/auth/callback/google',
      'Wrap your root layout with <SessionProvider> (see app/layout.oauth-example.js)',
      'Use requireAuth() from lib/auth-helpers for protected Server Components',
    ];
  },
};

function docContent(date, appDir) {
  return `# OAuth Setup Guide
> Generated by ai-scaffold on ${date}

## What is Auth.js (next-auth)?
Auth.js v5 (next-auth@beta) is the leading authentication library for Next.js. It supports 50+ OAuth providers, email magic links, and database sessions.

## What was set up
| Item | Detail |
|------|--------|
| Package | \`next-auth@beta\` (Auth.js v5) |
| \`auth.js\` | Auth config with GitHub + Google providers |
| \`${appDir}/api/auth/[...nextauth]/route.js\` | API route handler |
| \`lib/auth-helpers.js\` | \`requireAuth()\` and \`getSession()\` helpers |
| \`${appDir}/layout.oauth-example.js\` | Reference layout with SessionProvider |

## Environment Variables
| Variable | Description | Where to get it |
|----------|-------------|-----------------|
| \`AUTH_SECRET\` | Random secret for signing tokens | \`openssl rand -base64 32\` |
| \`AUTH_GITHUB_ID\` | GitHub OAuth App Client ID | GitHub → Settings → Developer Settings → OAuth Apps |
| \`AUTH_GITHUB_SECRET\` | GitHub OAuth App Client Secret | Same as above |
| \`AUTH_GOOGLE_ID\` | Google OAuth Client ID | Google Cloud Console → APIs & Services → Credentials |
| \`AUTH_GOOGLE_SECRET\` | Google OAuth Client Secret | Same as above |
| \`NEXTAUTH_URL\` | Your app's URL | \`http://localhost:3000\` for local |

## Usage

### Step 1: Wrap Layout with SessionProvider
Edit \`${appDir}/layout.js\`:
\`\`\`jsx
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
\`\`\`

### Server Components
\`\`\`js
import { requireAuth } from '@/lib/auth-helpers';

export default async function Dashboard() {
  const session = await requireAuth(); // redirects if not logged in
  return <div>Hello, {session.user.name}!</div>;
}
\`\`\`

### Client Components
\`\`\`jsx
'use client';
import { useSession, signIn, signOut } from 'next-auth/react';

export function AuthButton() {
  const { data: session } = useSession();

  if (session) {
    return (
      <>
        <span>{session.user.email}</span>
        <button onClick={() => signOut()}>Sign Out</button>
      </>
    );
  }
  return <button onClick={() => signIn()}>Sign In</button>;
}
\`\`\`

### Protecting API Routes
\`\`\`js
import { auth } from '@/auth';
import { NextResponse } from 'next/server';

export async function GET() {
  const session = await auth();
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  return NextResponse.json({ user: session.user });
}
\`\`\`

## Creating OAuth Apps

### GitHub
1. Go to https://github.com/settings/applications/new
2. Set "Authorization callback URL" to: \`https://yourdomain.com/api/auth/callback/github\`
3. Copy Client ID and Client Secret

### Google
1. Go to https://console.cloud.google.com
2. Create a project → APIs & Services → Credentials → Create OAuth 2.0 Client ID
3. Add authorized redirect URI: \`https://yourdomain.com/api/auth/callback/google\`
4. Copy Client ID and Client Secret

## Adding More Providers
\`\`\`js
import Twitter from 'next-auth/providers/twitter';
import Discord from 'next-auth/providers/discord';

// In auth.js providers array:
Twitter({ clientId: process.env.AUTH_TWITTER_ID, clientSecret: process.env.AUTH_TWITTER_SECRET }),
Discord({ clientId: process.env.AUTH_DISCORD_ID, clientSecret: process.env.AUTH_DISCORD_SECRET }),
\`\`\`

## Database Adapters
\`\`\`bash
npm install @auth/prisma-adapter
# or
npm install @auth/drizzle-adapter
\`\`\`

## Production Checklist
- [ ] Generate a strong AUTH_SECRET (\`openssl rand -base64 32\`)
- [ ] Set all env vars in your hosting environment
- [ ] Update OAuth callback URLs to your production domain
- [ ] Add your production domain to Google OAuth allowed origins
- [ ] Consider adding a database adapter for persistent sessions
- [ ] Set NEXTAUTH_URL to your production URL

## Troubleshooting
- **"AUTH_SECRET not set"**: Generate and set AUTH_SECRET environment variable
- **OAuth callback errors**: Verify callback URLs match exactly in your OAuth app settings
- **Session not persisting**: Check that SessionProvider wraps your layout

## Resources
- [Auth.js Docs](https://authjs.dev)
- [Next.js Guide](https://authjs.dev/getting-started/installation?framework=next.js)
- [Providers List](https://authjs.dev/getting-started/providers)
- [Database Adapters](https://authjs.dev/getting-started/adapters)
`;
}
