import { installStep, installDevStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'PlanetScale',
  description: 'Set up PlanetScale serverless MySQL with Drizzle ORM — branching database for production',
  category: 'Database — SQL (Managed Cloud)',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const dbFile = hasTypescript
      ? `import { drizzle } from 'drizzle-orm/planetscale-serverless';
import { connect } from '@planetscale/database';
import * as schema from './schema';

const connection = connect({
  url: process.env.DATABASE_URL!,
});

export const db = drizzle(connection, { schema });
`
      : `import { drizzle } from 'drizzle-orm/planetscale-serverless';
import { connect } from '@planetscale/database';
import * as schema from './schema.js';

const connection = connect({
  url: process.env.DATABASE_URL,
});

export const db = drizzle(connection, { schema });
`;

    const schemaFile = `import { mysqlTable, int, varchar, timestamp } from 'drizzle-orm/mysql-core';

export const users = mysqlTable('users', {
  id: int('id').primaryKey().autoincrement(),
  name: varchar('name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`;

    const drizzleConfig = hasTypescript
      ? `import type { Config } from 'drizzle-kit';

export default {
  schema: './lib/schema.ts',
  out: './drizzle',
  dialect: 'mysql',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
} satisfies Config;
`
      : `/** @type { import("drizzle-kit").Config } */
export default {
  schema: './lib/schema.js',
  out: './drizzle',
  dialect: 'mysql',
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
};
`;

    return [
      installStep(packageManager, ['@planetscale/database', 'drizzle-orm']),
      installDevStep(packageManager, ['drizzle-kit'], 'Install drizzle-kit (dev)'),
      {
        type: 'write',
        label: `Write lib/db.${ext}`,
        filePath: `lib/db.${ext}`,
        content: dbFile,
      },
      {
        type: 'write',
        label: `Write lib/schema.${ext}`,
        filePath: `lib/schema.${ext}`,
        content: schemaFile,
      },
      {
        type: 'write',
        label: `Write drizzle.config.${ext}`,
        filePath: `drizzle.config.${ext}`,
        content: drizzleConfig,
      },
      {
        type: 'env',
        label: 'Add DATABASE_URL to .env.example',
        vars: {
          DATABASE_URL: 'mysql://user:password@aws.connect.psdb.cloud/dbname?sslaccept=strict',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/planetscale.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Create a database at https://app.planetscale.com',
      'Create a password (Settings → Passwords → New Password)',
      'Copy the connection string into DATABASE_URL in .env',
      'Push your schema: `npx drizzle-kit push`',
      'Use branches for schema changes: `pscale branch create <db> <branch>`',
    ];
  },
};

function docContent(date) {
  return `# PlanetScale Setup Guide
> Generated by ai-scaffold on ${date}

## What is PlanetScale?
PlanetScale is a serverless MySQL platform with Git-style database branching. You can develop schema changes in branches and merge them safely, with zero-downtime deploys.

## What was set up
| Item | Detail |
|------|--------|
| Packages | \`@planetscale/database\`, \`drizzle-orm\` |
| Dev packages | \`drizzle-kit\` |
| \`lib/db.js\` | Drizzle client using PlanetScale serverless driver |
| \`lib/schema.js\` | Example users table (MySQL dialect) |
| \`drizzle.config.js\` | Drizzle Kit configuration |

## Environment Variables
| Variable | Description | Where to get it |
|----------|-------------|-----------------|
| \`DATABASE_URL\` | PlanetScale connection string | App → Settings → Passwords |

## Usage

### Querying
\`\`\`js
import { db } from '@/lib/db';
import { users } from '@/lib/schema';
import { eq } from 'drizzle-orm';

const allUsers = await db.select().from(users);
await db.insert(users).values({ name: 'Alice', email: 'alice@example.com' });
await db.update(users).set({ name: 'Bob' }).where(eq(users.id, 1));
await db.delete(users).where(eq(users.id, 1));
\`\`\`

## PlanetScale CLI Branching Workflow
\`\`\`bash
# Install CLI
brew install planetscale/tap/pscale

# Create a dev branch
pscale branch create mydb add-posts-table

# Connect to branch locally
pscale connect mydb add-posts-table --port 3309

# Push schema to branch
DATABASE_URL="mysql://root@127.0.0.1:3309/mydb" npx drizzle-kit push

# Create a deploy request (like a PR for your schema)
pscale deploy-request create mydb add-posts-table

# Deploy to production
pscale deploy-request deploy mydb <number>
\`\`\`

## Production Checklist
- [ ] Create your database at https://app.planetscale.com
- [ ] Use branches for all schema changes
- [ ] Create a production password with limited permissions
- [ ] Set DATABASE_URL in your hosting environment
- [ ] Enable safe migrations in PlanetScale settings

## Resources
- [PlanetScale Docs](https://planetscale.com/docs)
- [PlanetScale + Drizzle](https://orm.drizzle.team/docs/get-started-mysql#planetscale)
- [PlanetScale CLI](https://planetscale.com/docs/reference/planetscale-cli)
`;
}
