const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Plausible Analytics',
  description: 'Set up Plausible — privacy-first, GDPR-compliant analytics with no cookies',
  category: 'Analytics',
  supportedFrameworks: ['nextjs', 'react'],

  steps(context) {
    const { hasTypescript } = context;
    const ext = hasTypescript ? 'ts' : 'js';
    const appDir = context.usesSrcDir ? 'src/app' : 'app';

    const plausibleScript = `// components/PlausibleScript.jsx
// Add this component to your root layout
import Script from 'next/script';

export function PlausibleScript() {
  const domain = process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN;
  if (!domain) return null;

  return (
    <Script
      defer
      data-domain={domain}
      src="https://plausible.io/js/script.js"
      strategy="afterInteractive"
    />
  );
}
`;

    const analyticsHelper = hasTypescript
      ? `// Client-side Plausible event tracking
// Plausible injects a global window.plausible function via the script tag

declare global {
  interface Window {
    plausible?: (event: string, options?: { props?: Record<string, string | number | boolean> }) => void;
  }
}

/**
 * Track a custom event in Plausible.
 * Only works in the browser (client components).
 */
export function trackEvent(
  event: string,
  props?: Record<string, string | number | boolean>
): void {
  if (typeof window === 'undefined') return;
  if (!window.plausible) return;
  window.plausible(event, { props });
}

// ─── Common event helpers ─────────────────────────────────

export const analytics = {
  signUp: () => trackEvent('Sign Up'),
  signIn: () => trackEvent('Sign In'),
  upgrade: (plan: string) => trackEvent('Upgrade', { plan }),
  buttonClick: (label: string) => trackEvent('Button Click', { label }),
  formSubmit: (name: string) => trackEvent('Form Submit', { name }),
  download: (file: string) => trackEvent('Download', { file }),
};
`
      : `declare global {
  interface Window {
    plausible?: (event: string, options?: { props?: Record<string, string | number | boolean> }) => void;
  }
}

export function trackEvent(event, props) {
  if (typeof window === 'undefined') return;
  if (!window.plausible) return;
  window.plausible(event, { props });
}

export const analytics = {
  signUp: () => trackEvent('Sign Up'),
  signIn: () => trackEvent('Sign In'),
  upgrade: (plan) => trackEvent('Upgrade', { plan }),
  buttonClick: (label) => trackEvent('Button Click', { label }),
  formSubmit: (name) => trackEvent('Form Submit', { name }),
  download: (file) => trackEvent('Download', { file }),
};
`;

    return [
      {
        type: 'write',
        label: `Write components/PlausibleScript.${ext}x`,
        filePath: `components/PlausibleScript.${ext}x`,
        content: plausibleScript,
      },
      {
        type: 'write',
        label: `Write lib/analytics.${ext}`,
        filePath: `lib/analytics.${ext}`,
        content: analyticsHelper,
      },
      {
        type: 'env',
        label: 'Add Plausible env vars to .env.example',
        vars: {
          NEXT_PUBLIC_PLAUSIBLE_DOMAIN: 'yourdomain.com',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/plausible.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Create an account at https://plausible.io (free trial, then paid)',
      'Or self-host: https://plausible.io/self-hosted',
      'Add your domain in Plausible → Add Website',
      'Set NEXT_PUBLIC_PLAUSIBLE_DOMAIN to your domain (e.g., yourdomain.com)',
      'Add <PlausibleScript /> to your root layout',
      'Track custom events with trackEvent() or analytics.signUp() etc.',
    ];
  },
};

function docContent(date) {
  return `# Plausible Analytics Setup Guide
> Generated by ai-scaffold on ${date}

## What was set up
| Item | Detail |
|------|--------|
| \`components/PlausibleScript.jsx\` | Script tag for Plausible (no external packages needed) |
| \`lib/analytics.js\` | trackEvent() + common helpers |

## Setup

### Add to root layout
\`\`\`jsx
// app/layout.js
import { PlausibleScript } from '@/components/PlausibleScript';

export default function RootLayout({ children }) {
  return (
    <html>
      <head><PlausibleScript /></head>
      <body>{children}</body>
    </html>
  );
}
\`\`\`

### Track custom events
\`\`\`jsx
'use client';
import { analytics } from '@/lib/analytics';

<button onClick={() => analytics.upgrade('pro')}>Upgrade</button>
<button onClick={() => analytics.buttonClick('hero-cta')}>Get Started</button>
\`\`\`

## Resources
- [Plausible Docs](https://plausible.io/docs)
- [Custom Events](https://plausible.io/docs/custom-event-goals)
- [Self-Hosting](https://plausible.io/self-hosted)
`;
}
