import { installStep, installDevStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'PostgreSQL (Local Docker)',
  description: 'Set up a local PostgreSQL database via Docker with pg + Drizzle ORM',
  category: 'Database — SQL (Local)',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const dockerCompose = `version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
`;

    const dbFile = hasTypescript
      ? `import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from './schema';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL!,
});

export const db = drizzle(pool, { schema });
`
      : `import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from './schema.js';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

export const db = drizzle(pool, { schema });
`;

    const schemaFile = hasTypescript
      ? `import { pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`
      : `import { pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
`;

    const drizzleConfig = hasTypescript
      ? `import type { Config } from 'drizzle-kit';

export default {
  schema: './lib/schema.ts',
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
} satisfies Config;
`
      : `/** @type { import("drizzle-kit").Config } */
export default {
  schema: './lib/schema.js',
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
};
`;

    return [
      installStep(packageManager, ['pg', 'drizzle-orm']),
      installDevStep(packageManager, ['drizzle-kit', '@types/pg'], 'Install drizzle-kit, @types/pg (dev)'),
      {
        type: 'write',
        label: 'Write docker-compose.postgres.yml',
        filePath: 'docker-compose.postgres.yml',
        content: dockerCompose,
      },
      {
        type: 'write',
        label: `Write lib/db.${ext}`,
        filePath: `lib/db.${ext}`,
        content: dbFile,
      },
      {
        type: 'write',
        label: `Write lib/schema.${ext}`,
        filePath: `lib/schema.${ext}`,
        content: schemaFile,
      },
      {
        type: 'write',
        label: `Write drizzle.config.${ext}`,
        filePath: `drizzle.config.${ext}`,
        content: drizzleConfig,
      },
      {
        type: 'env',
        label: 'Add DATABASE_URL to .env.example',
        vars: {
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/myapp',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/postgres.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Start Postgres: `docker compose -f docker-compose.postgres.yml up -d`',
      'Copy .env.example to .env and verify DATABASE_URL',
      'Push your schema: `npx drizzle-kit push`',
      'Open Drizzle Studio: `npx drizzle-kit studio`',
      'Import { db } from "@/lib/db" to query your database',
    ];
  },
};

function docContent(date) {
  return `# PostgreSQL Setup Guide
> Generated by ai-scaffold on ${date}

## What was set up
| Item | Detail |
|------|--------|
| Packages | \`pg\`, \`drizzle-orm\` |
| Dev packages | \`drizzle-kit\`, \`@types/pg\` |
| \`docker-compose.postgres.yml\` | Local Postgres 16 container |
| \`lib/db.js\` | Drizzle client using node-postgres pool |
| \`lib/schema.js\` | Example users table |
| \`drizzle.config.js\` | Drizzle Kit configuration |

## Environment Variables
| Variable | Description |
|----------|-------------|
| \`DATABASE_URL\` | PostgreSQL connection string |

## Usage

### Start local database
\`\`\`bash
docker compose -f docker-compose.postgres.yml up -d
\`\`\`

### Querying with Drizzle
\`\`\`js
import { db } from '@/lib/db';
import { users } from '@/lib/schema';
import { eq } from 'drizzle-orm';

// Select all users
const allUsers = await db.select().from(users);

// Insert a user
await db.insert(users).values({ name: 'Alice', email: 'alice@example.com' });

// Update
await db.update(users).set({ name: 'Bob' }).where(eq(users.id, 1));

// Delete
await db.delete(users).where(eq(users.id, 1));
\`\`\`

### Schema Management
\`\`\`bash
# Push schema changes (no migration files)
npx drizzle-kit push

# Generate migration files
npx drizzle-kit generate

# Apply migrations
npx drizzle-kit migrate

# Open visual DB browser
npx drizzle-kit studio
\`\`\`

## Adding Tables
\`\`\`js
import { pgTable, serial, text, integer, boolean } from 'drizzle-orm/pg-core';

export const posts = pgTable('posts', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  userId: integer('user_id').references(() => users.id),
  published: boolean('published').default(false),
});
\`\`\`

## Production Checklist
- [ ] Use a managed provider (Neon, Railway, Supabase, RDS)
- [ ] Set DATABASE_URL in your hosting environment
- [ ] Enable SSL: add \`?sslmode=require\` to your connection string
- [ ] Set up automated backups
- [ ] Use connection pooling (PgBouncer or Neon pooled connection)

## Docker Commands
\`\`\`bash
# Start
docker compose -f docker-compose.postgres.yml up -d

# View logs
docker compose -f docker-compose.postgres.yml logs -f

# Stop
docker compose -f docker-compose.postgres.yml down

# Stop + remove all data
docker compose -f docker-compose.postgres.yml down -v

# Connect with psql
docker exec -it <container-name> psql -U postgres -d myapp
\`\`\`

## Resources
- [Drizzle ORM Docs](https://orm.drizzle.team)
- [node-postgres Docs](https://node-postgres.com)
- [PostgreSQL Docs](https://www.postgresql.org/docs)
`;
}
