import { installStep, installDevStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Prisma',
  description: 'Set up Prisma ORM with schema, migrations, seed script, and typed client',
  category: 'ORM / Database Tools',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const schema = `// This is your Prisma schema file
// Learn more: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map("users")
}
`;

    const dbClient = hasTypescript
      ? `import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['query', 'error', 'warn'] : ['error'],
  });

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;
`
      : `import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis;

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['query', 'error', 'warn'] : ['error'],
  });

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;
`;

    const seedFile = hasTypescript
      ? `import { prisma } from '../lib/prisma';

async function main() {
  console.log('Seeding database...');

  await prisma.user.upsert({
    where: { email: 'alice@example.com' },
    update: {},
    create: {
      email: 'alice@example.com',
      name: 'Alice',
    },
  });

  await prisma.user.upsert({
    where: { email: 'bob@example.com' },
    update: {},
    create: {
      email: 'bob@example.com',
      name: 'Bob',
    },
  });

  console.log('Seeding done.');
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
`
      : `import { prisma } from '../lib/prisma.js';

async function main() {
  console.log('Seeding database...');

  await prisma.user.upsert({
    where: { email: 'alice@example.com' },
    update: {},
    create: { email: 'alice@example.com', name: 'Alice' },
  });

  await prisma.user.upsert({
    where: { email: 'bob@example.com' },
    update: {},
    create: { email: 'bob@example.com', name: 'Bob' },
  });

  console.log('Seeding done.');
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
`;

    return [
      installStep(packageManager, ['@prisma/client']),
      installDevStep(packageManager, ['prisma'], 'Install prisma CLI (dev)'),
      {
        type: 'exec',
        label: 'Initialize Prisma',
        command: 'npx prisma init --datasource-provider postgresql',
        cwd: context.projectDir,
      },
      {
        type: 'write',
        label: 'Write prisma/schema.prisma',
        filePath: 'prisma/schema.prisma',
        content: schema,
      },
      {
        type: 'write',
        label: `Write lib/prisma.${ext}`,
        filePath: `lib/prisma.${ext}`,
        content: dbClient,
      },
      {
        type: 'write',
        label: `Write prisma/seed.${ext}`,
        filePath: `prisma/seed.${ext}`,
        content: seedFile,
      },
      {
        type: 'env',
        label: 'Add DATABASE_URL to .env.example',
        vars: {
          DATABASE_URL: 'postgresql://user:password@localhost:5432/myapp?schema=public',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/prisma.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Set your DATABASE_URL in .env',
      'Edit prisma/schema.prisma to define your data model',
      'Run `npx prisma migrate dev --name init` to create and apply your first migration',
      'Run `npx prisma db seed` to seed the database',
      'Run `npx prisma studio` to open the visual DB editor',
      'Import { prisma } from "@/lib/prisma" to query your database',
    ];
  },
};

function docContent(date) {
  return `# Prisma Setup Guide
> Generated by ai-scaffold on ${date}

## What was set up
| Item | Detail |
|------|--------|
| Package | \`@prisma/client\` |
| Dev package | \`prisma\` (CLI) |
| \`prisma/schema.prisma\` | Data model with example User model |
| \`lib/prisma.js\` | Singleton Prisma client (safe for Next.js HMR) |
| \`prisma/seed.js\` | Database seed script |

## Environment Variables
| Variable | Description |
|----------|-------------|
| \`DATABASE_URL\` | Database connection string |

## Usage

### Querying
\`\`\`js
import { prisma } from '@/lib/prisma';

// Find all
const users = await prisma.user.findMany();

// Find one
const user = await prisma.user.findUnique({ where: { email: 'alice@example.com' } });

// Create
const newUser = await prisma.user.create({
  data: { email: 'alice@example.com', name: 'Alice' },
});

// Update
await prisma.user.update({ where: { id: 1 }, data: { name: 'Bob' } });

// Delete
await prisma.user.delete({ where: { id: 1 } });

// Relations
const userWithPosts = await prisma.user.findUnique({
  where: { id: 1 },
  include: { posts: true },
});
\`\`\`

### Migrations
\`\`\`bash
# Create and apply a migration
npx prisma migrate dev --name add_posts_table

# Apply migrations in production
npx prisma migrate deploy

# Reset DB (dev only — wipes data)
npx prisma migrate reset

# Open Prisma Studio
npx prisma studio

# Seed
npx prisma db seed
\`\`\`

### Adding a model
\`\`\`prisma
model Post {
  id        Int      @id @default(autoincrement())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
  createdAt DateTime @default(now())
}
\`\`\`
Then run: \`npx prisma migrate dev --name add_posts\`

## Production Checklist
- [ ] Run \`npx prisma migrate deploy\` in your CI/CD pipeline
- [ ] Never run \`migrate dev\` in production
- [ ] Set DATABASE_URL in your hosting env
- [ ] Add \`prisma generate\` to your build step
- [ ] Review and enable connection pooling for serverless

## Resources
- [Prisma Docs](https://www.prisma.io/docs)
- [Prisma Schema Reference](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference)
- [Prisma with Next.js](https://www.prisma.io/nextjs)
`;
}
