import { installStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Redis (Local Docker)',
  description: 'Set up a local Redis via Docker with ioredis client — for caching, queues, and pub/sub',
  category: 'Database — NoSQL',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const dockerCompose = `version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass "\${REDIS_PASSWORD:-}"

volumes:
  redis_data:
`;

    const redisClient = hasTypescript
      ? `import Redis from 'ioredis';

let client: Redis | null = null;

export function getRedis(): Redis {
  if (!client) {
    client = new Redis(process.env.REDIS_URL ?? 'redis://localhost:6379', {
      maxRetriesPerRequest: 3,
      lazyConnect: true,
    });

    client.on('error', (err) => console.error('Redis error:', err));
    client.on('connect', () => console.log('Redis connected'));
  }
  return client;
}

export const redis = getRedis();

// ─── Cache helpers ────────────────────────────────────────

export async function cacheSet<T>(key: string, value: T, ttlSeconds?: number): Promise<void> {
  const serialized = JSON.stringify(value);
  if (ttlSeconds) {
    await redis.setex(key, ttlSeconds, serialized);
  } else {
    await redis.set(key, serialized);
  }
}

export async function cacheGet<T>(key: string): Promise<T | null> {
  const raw = await redis.get(key);
  if (!raw) return null;
  try { return JSON.parse(raw); } catch { return raw as unknown as T; }
}

export async function cacheDel(...keys: string[]): Promise<void> {
  await redis.del(...keys);
}

export async function cacheInvalidatePrefix(prefix: string): Promise<void> {
  const keys = await redis.keys(\`\${prefix}*\`);
  if (keys.length > 0) await redis.del(...keys);
}
`
      : `import Redis from 'ioredis';

let client = null;

export function getRedis() {
  if (!client) {
    client = new Redis(process.env.REDIS_URL ?? 'redis://localhost:6379', {
      maxRetriesPerRequest: 3,
      lazyConnect: true,
    });
    client.on('error', (err) => console.error('Redis error:', err));
    client.on('connect', () => console.log('Redis connected'));
  }
  return client;
}

export const redis = getRedis();

export async function cacheSet(key, value, ttlSeconds) {
  const serialized = JSON.stringify(value);
  if (ttlSeconds) {
    await redis.setex(key, ttlSeconds, serialized);
  } else {
    await redis.set(key, serialized);
  }
}

export async function cacheGet(key) {
  const raw = await redis.get(key);
  if (!raw) return null;
  try { return JSON.parse(raw); } catch { return raw; }
}

export async function cacheDel(...keys) {
  await redis.del(...keys);
}

export async function cacheInvalidatePrefix(prefix) {
  const keys = await redis.keys(\`\${prefix}*\`);
  if (keys.length > 0) await redis.del(...keys);
}
`;

    return [
      installStep(packageManager, ['ioredis']),
      {
        type: 'write',
        label: 'Write docker-compose.redis.yml',
        filePath: 'docker-compose.redis.yml',
        content: dockerCompose,
      },
      {
        type: 'write',
        label: `Write lib/redis.${ext}`,
        filePath: `lib/redis.${ext}`,
        content: redisClient,
      },
      {
        type: 'env',
        label: 'Add Redis env vars to .env.example',
        vars: {
          REDIS_URL: 'redis://localhost:6379',
          REDIS_PASSWORD: '',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/redis-local.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Start Redis: `docker compose -f docker-compose.redis.yml up -d`',
      'Import { redis } from "@/lib/redis" for direct commands',
      'Import { cacheSet, cacheGet } from "@/lib/redis" for caching',
      'For background jobs, pair with BullMQ: `just-start-dude setup bullmq`',
    ];
  },
};

function docContent(date) {
  return `# Redis (Local) Setup Guide
> Generated by ai-scaffold on ${date}

## What was set up
| Item | Detail |
|------|--------|
| Package | \`ioredis\` |
| \`docker-compose.redis.yml\` | Redis 7 with persistence (AOF) |
| \`lib/redis.js\` | ioredis singleton + cache helpers |

## Usage

### Caching
\`\`\`js
import { cacheSet, cacheGet, cacheDel, cacheInvalidatePrefix } from '@/lib/redis';

await cacheSet('user:1', { name: 'Alice' }, 300); // TTL: 5 min
const user = await cacheGet('user:1');             // { name: 'Alice' } | null
await cacheDel('user:1');
await cacheInvalidatePrefix('user:');              // delete all user:* keys
\`\`\`

### Direct commands
\`\`\`js
import { redis } from '@/lib/redis';

await redis.set('key', 'value');
await redis.incr('page_views');
await redis.lpush('queue', 'job1');
await redis.publish('channel', 'message');
\`\`\`

## Resources
- [ioredis Docs](https://github.com/redis/ioredis)
- [Redis Commands](https://redis.io/commands)
`;
}
