const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'shadcn/ui',
  description: 'Set up shadcn/ui component library with all base components',
  supportedFrameworks: ['nextjs', 'react'],

  steps(context) {
    return [
      {
        type: 'exec',
        label: 'Initialize shadcn/ui',
        command: 'npx shadcn@latest init --yes',
        cwd: context.projectDir,
      },
      {
        type: 'exec',
        label: 'Add all shadcn/ui components',
        command: 'npx shadcn@latest add --all --yes',
        cwd: context.projectDir,
      },
      {
        type: 'doc',
        label: 'Write docs/shadcn.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Components are in components/ui/ — import them directly',
      'Customize the theme in tailwind.config.js or globals.css CSS variables',
      'Add individual components with: npx shadcn@latest add <component>',
      'Browse all components at https://ui.shadcn.com/docs/components',
    ];
  },
};

function docContent(date) {
  return `# shadcn/ui Setup Guide
> Generated by ai-scaffold on ${date}

## What is shadcn/ui?
shadcn/ui is a collection of beautifully designed, accessible React components built on Radix UI and Tailwind CSS. Components are copied into your codebase so you own them completely.

## What was set up
| Item | Detail |
|------|--------|
| shadcn/ui | Initialized via \`npx shadcn@latest init\` |
| All components | Added via \`npx shadcn@latest add --all\` |
| \`components/ui/\` | All UI components live here |
| \`tailwind.config.js\` | Updated with shadcn theme |
| \`globals.css\` | CSS variables for theming |

## Usage

### Importing Components
\`\`\`jsx
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';

export default function Example() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Login</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Input placeholder="Email" type="email" />
        <Input placeholder="Password" type="password" />
        <Button className="w-full">Sign In</Button>
      </CardContent>
    </Card>
  );
}
\`\`\`

### Adding Individual Components
\`\`\`bash
npx shadcn@latest add button
npx shadcn@latest add card
npx shadcn@latest add dialog
npx shadcn@latest add form
\`\`\`

## Theming
Edit CSS variables in \`app/globals.css\` (or \`styles/globals.css\`):
\`\`\`css
:root {
  --background: 0 0% 100%;
  --foreground: 222.2 84% 4.9%;
  --primary: 222.2 47.4% 11.2%;
  --primary-foreground: 210 40% 98%;
  /* ... */
}

.dark {
  --background: 222.2 84% 4.9%;
  --foreground: 210 40% 98%;
  /* ... */
}
\`\`\`

## Production Checklist
- [ ] Review and remove any unused components from components/ui/
- [ ] Customize the color palette in globals.css
- [ ] Test accessibility with a screen reader
- [ ] Verify dark mode works correctly

## Troubleshooting
- **Components not found**: Run \`npx shadcn@latest add <component>\` to add missing components
- **Styles not applying**: Ensure Tailwind is configured to scan your component files
- **Dark mode not working**: Add \`dark\` class to \`<html>\` or use next-themes

## Resources
- [shadcn/ui Docs](https://ui.shadcn.com)
- [Component List](https://ui.shadcn.com/docs/components)
- [Theming Guide](https://ui.shadcn.com/docs/theming)
- [Dark Mode](https://ui.shadcn.com/docs/dark-mode)
`;
}
