import { installStep, installDevStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'SQLite',
  description: 'Set up local SQLite with better-sqlite3 + Drizzle ORM — zero setup, file-based DB',
  category: 'Database — SQL (Local)',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const dbFile = hasTypescript
      ? `import { drizzle } from 'drizzle-orm/better-sqlite3';
import Database from 'better-sqlite3';
import * as schema from './schema';

const sqlite = new Database(process.env.DATABASE_PATH ?? 'local.db');
export const db = drizzle(sqlite, { schema });
`
      : `import { drizzle } from 'drizzle-orm/better-sqlite3';
import Database from 'better-sqlite3';
import * as schema from './schema.js';

const sqlite = new Database(process.env.DATABASE_PATH ?? 'local.db');
export const db = drizzle(sqlite, { schema });
`;

    const schemaFile = `import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: integer('created_at', { mode: 'timestamp' })
    .$defaultFn(() => new Date())
    .notNull(),
});
`;

    const drizzleConfig = hasTypescript
      ? `import type { Config } from 'drizzle-kit';

export default {
  schema: './lib/schema.ts',
  out: './drizzle',
  dialect: 'sqlite',
  dbCredentials: {
    url: process.env.DATABASE_PATH ?? 'local.db',
  },
} satisfies Config;
`
      : `/** @type { import("drizzle-kit").Config } */
export default {
  schema: './lib/schema.js',
  out: './drizzle',
  dialect: 'sqlite',
  dbCredentials: {
    url: process.env.DATABASE_PATH ?? 'local.db',
  },
};
`;

    const gitignoreAppend = `
# SQLite database files
*.db
*.db-shm
*.db-wal
`;

    return [
      installStep(packageManager, ['better-sqlite3', 'drizzle-orm']),
      installDevStep(packageManager, ['drizzle-kit', '@types/better-sqlite3'], 'Install drizzle-kit, @types/better-sqlite3 (dev)'),
      {
        type: 'write',
        label: `Write lib/db.${ext}`,
        filePath: `lib/db.${ext}`,
        content: dbFile,
      },
      {
        type: 'write',
        label: `Write lib/schema.${ext}`,
        filePath: `lib/schema.${ext}`,
        content: schemaFile,
      },
      {
        type: 'write',
        label: `Write drizzle.config.${ext}`,
        filePath: `drizzle.config.${ext}`,
        content: drizzleConfig,
      },
      {
        type: 'env',
        label: 'Add DATABASE_PATH to .env.example',
        vars: {
          DATABASE_PATH: 'local.db',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/sqlite.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'No Docker needed — SQLite is file-based and works immediately',
      'Push your schema: `npx drizzle-kit push`',
      'Open Drizzle Studio: `npx drizzle-kit studio`',
      'Import { db } from "@/lib/db" to query your database',
      'Add *.db to your .gitignore to avoid committing the database file',
      'For production, consider migrating to a hosted Postgres or Turso (SQLite at the edge)',
    ];
  },
};

function docContent(date) {
  return `# SQLite Setup Guide
> Generated by ai-scaffold on ${date}

## What was set up
| Item | Detail |
|------|--------|
| Packages | \`better-sqlite3\`, \`drizzle-orm\` |
| Dev packages | \`drizzle-kit\`, \`@types/better-sqlite3\` |
| \`lib/db.js\` | Drizzle client backed by a local SQLite file |
| \`lib/schema.js\` | Example users table |
| \`drizzle.config.js\` | Drizzle Kit configuration |

## Environment Variables
| Variable | Description |
|----------|-------------|
| \`DATABASE_PATH\` | Path to the SQLite file (default: \`local.db\`) |

## Usage

### Querying with Drizzle
\`\`\`js
import { db } from '@/lib/db';
import { users } from '@/lib/schema';
import { eq } from 'drizzle-orm';

// Synchronous by default with better-sqlite3
const allUsers = db.select().from(users).all();
await db.insert(users).values({ name: 'Alice', email: 'alice@example.com' });
await db.update(users).set({ name: 'Bob' }).where(eq(users.id, 1));
await db.delete(users).where(eq(users.id, 1));
\`\`\`

### Schema Management
\`\`\`bash
npx drizzle-kit push     # push schema changes
npx drizzle-kit studio   # visual DB browser
npx drizzle-kit generate # generate migration files
\`\`\`

## .gitignore
Add to your \`.gitignore\`:
\`\`\`
*.db
*.db-shm
*.db-wal
\`\`\`

## Production Notes
SQLite is ideal for:
- Local development and prototyping
- Single-server deployments with low write concurrency
- CLI tools and embedded apps

For serverless or multi-region deployments, consider **Turso** (\`just-start-dude setup turso\`) — it's SQLite at the edge.

## Resources
- [Drizzle + SQLite Docs](https://orm.drizzle.team/docs/get-started-sqlite)
- [better-sqlite3 Docs](https://github.com/WiseLibs/better-sqlite3)
`;
}
