const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Supabase',
  description: 'Set up Supabase with a typed client helper and local Docker stack',
  supportedFrameworks: ['nextjs', 'react', 'express'],

  steps(context) {
    const { hasTypescript, usesAppRouter } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const browserClient = hasTypescript
      ? `import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
`
      : `import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
`;

    const serverClient = hasTypescript
      ? `import { createClient } from '@supabase/supabase-js';

export function createServerClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
}
`
      : `import { createClient } from '@supabase/supabase-js';

export function createServerClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY
  );
}
`;

    const configToml = `# A string used to distinguish different Supabase projects on the same host.
project_id = "my-project"

[api]
port = 54321

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
`;

    const steps = [
      {
        type: 'exec',
        label: 'Install @supabase/supabase-js',
        command: 'npm install @supabase/supabase-js',
        cwd: context.projectDir,
      },
      {
        type: 'exec',
        label: 'Install supabase CLI (dev)',
        command: 'npm install --save-dev supabase',
        cwd: context.projectDir,
      },
      {
        type: 'write',
        label: `Write lib/supabase.${ext}`,
        filePath: `lib/supabase.${ext}`,
        content: browserClient,
      },
      {
        type: 'write',
        label: 'Write supabase/config.toml',
        filePath: 'supabase/config.toml',
        content: configToml,
      },
      {
        type: 'env',
        label: 'Add env vars to .env.example',
        vars: {
          NEXT_PUBLIC_SUPABASE_URL: 'https://your-project.supabase.co',
          NEXT_PUBLIC_SUPABASE_ANON_KEY: 'your-anon-key',
          SUPABASE_SERVICE_ROLE_KEY: 'your-service-role-key',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/supabase.md',
        content: docContent(DATE),
      },
    ];

    if (usesAppRouter) {
      steps.splice(3, 0, {
        type: 'write',
        label: `Write lib/supabase-server.${ext}`,
        filePath: `lib/supabase-server.${ext}`,
        content: serverClient,
      });
    }

    return steps;
  },

  nextSteps(context) {
    const steps = [
      'Create a Supabase project at https://supabase.com',
      'Copy your project URL and anon key into .env.example (rename to .env.local)',
      'Run `npx supabase init` to initialize the local CLI config',
      'Run `npx supabase start` to spin up local Supabase (requires Docker)',
    ];
    if (context.usesAppRouter) {
      steps.push('Use createServerClient() from lib/supabase-server for Server Components');
    }
    steps.push('Use the supabase client from lib/supabase for client-side queries');
    return steps;
  },
};

function docContent(date) {
  return `# Supabase Setup Guide
> Generated by ai-scaffold on ${date}

## What is Supabase?
Supabase is an open-source Firebase alternative providing a Postgres database, authentication, real-time subscriptions, and storage.

## What was set up
| Item | Detail |
|------|--------|
| Package | \`@supabase/supabase-js\` |
| Dev package | \`supabase\` CLI |
| \`lib/supabase.js\` | Browser/client Supabase client |
| \`lib/supabase-server.js\` | Server-side client (Next.js App Router) |
| \`supabase/config.toml\` | Local Docker stack config |

## Environment Variables
| Variable | Description | Where to get it |
|----------|-------------|-----------------|
| \`NEXT_PUBLIC_SUPABASE_URL\` | Your project's API URL | Supabase dashboard → Settings → API |
| \`NEXT_PUBLIC_SUPABASE_ANON_KEY\` | Public anon key (safe for browser) | Supabase dashboard → Settings → API |
| \`SUPABASE_SERVICE_ROLE_KEY\` | Secret service role key | Supabase dashboard → Settings → API |

## Usage

### Client Components
\`\`\`js
import { supabase } from '@/lib/supabase';

const { data, error } = await supabase.from('users').select('*');
\`\`\`

### Server Components (App Router)
\`\`\`js
import { createServerClient } from '@/lib/supabase-server';

export default async function Page() {
  const supabase = createServerClient();
  const { data } = await supabase.from('users').select('*');
  return <pre>{JSON.stringify(data, null, 2)}</pre>;
}
\`\`\`

### Auth
\`\`\`js
// Sign up
await supabase.auth.signUp({ email, password });

// Sign in
await supabase.auth.signInWithPassword({ email, password });

// Sign out
await supabase.auth.signOut();

// Get user
const { data: { user } } = await supabase.auth.getUser();
\`\`\`

## Local Development
\`\`\`bash
# Initialize Supabase (creates supabase/ directory)
npx supabase init

# Start local stack (requires Docker)
npx supabase start

# Stop local stack
npx supabase stop

# Run migrations
npx supabase db push
\`\`\`

## Production Checklist
- [ ] Create a Supabase project at https://supabase.com
- [ ] Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in your hosting env
- [ ] Set SUPABASE_SERVICE_ROLE_KEY in your hosting env (server-only)
- [ ] Enable Row Level Security (RLS) on all tables
- [ ] Set up auth redirect URLs in Supabase dashboard
- [ ] Configure SMTP for production emails

## Troubleshooting
- **"Invalid API key"**: Check that your env vars are set correctly and restart dev server
- **CORS errors**: Add your frontend URL to Supabase dashboard → Authentication → URL Configuration
- **RLS blocking queries**: Temporarily disable RLS in dev or add policies

## Resources
- [Supabase Docs](https://supabase.com/docs)
- [Supabase JavaScript Client](https://supabase.com/docs/reference/javascript)
- [Row Level Security](https://supabase.com/docs/guides/database/postgres/row-level-security)
- [Auth Helpers for Next.js](https://supabase.com/docs/guides/auth/auth-helpers/nextjs)
`;
}
