import { installStep, installDevStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Turso',
  description: 'Set up Turso — SQLite at the edge with libSQL, Drizzle ORM, and sub-ms reads globally',
  category: 'Database — SQL (Managed Cloud)',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const dbFile = hasTypescript
      ? `import { drizzle } from 'drizzle-orm/libsql';
import { createClient } from '@libsql/client';
import * as schema from './schema';

const client = createClient({
  url: process.env.TURSO_DATABASE_URL!,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

export const db = drizzle(client, { schema });
`
      : `import { drizzle } from 'drizzle-orm/libsql';
import { createClient } from '@libsql/client';
import * as schema from './schema.js';

const client = createClient({
  url: process.env.TURSO_DATABASE_URL,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

export const db = drizzle(client, { schema });
`;

    const schemaFile = `import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  createdAt: integer('created_at', { mode: 'timestamp' })
    .$defaultFn(() => new Date())
    .notNull(),
});
`;

    const drizzleConfig = hasTypescript
      ? `import type { Config } from 'drizzle-kit';

export default {
  schema: './lib/schema.ts',
  out: './drizzle',
  dialect: 'turso',
  dbCredentials: {
    url: process.env.TURSO_DATABASE_URL!,
    authToken: process.env.TURSO_AUTH_TOKEN,
  },
} satisfies Config;
`
      : `/** @type { import("drizzle-kit").Config } */
export default {
  schema: './lib/schema.js',
  out: './drizzle',
  dialect: 'turso',
  dbCredentials: {
    url: process.env.TURSO_DATABASE_URL,
    authToken: process.env.TURSO_AUTH_TOKEN,
  },
};
`;

    return [
      installStep(packageManager, ['@libsql/client', 'drizzle-orm']),
      installDevStep(packageManager, ['drizzle-kit'], 'Install drizzle-kit (dev)'),
      {
        type: 'write',
        label: `Write lib/db.${ext}`,
        filePath: `lib/db.${ext}`,
        content: dbFile,
      },
      {
        type: 'write',
        label: `Write lib/schema.${ext}`,
        filePath: `lib/schema.${ext}`,
        content: schemaFile,
      },
      {
        type: 'write',
        label: `Write drizzle.config.${ext}`,
        filePath: `drizzle.config.${ext}`,
        content: drizzleConfig,
      },
      {
        type: 'env',
        label: 'Add Turso env vars to .env.example',
        vars: {
          TURSO_DATABASE_URL: 'libsql://your-database.turso.io',
          TURSO_AUTH_TOKEN: 'your-turso-auth-token',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/turso.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Install Turso CLI: `curl -sSfL https://get.tur.so/install.sh | bash`',
      'Login: `turso auth login`',
      'Create a database: `turso db create myapp`',
      'Get the URL: `turso db show myapp --url`',
      'Get a token: `turso db tokens create myapp`',
      'Push your schema: `npx drizzle-kit push`',
    ];
  },
};

function docContent(date) {
  return `# Turso Setup Guide
> Generated by ai-scaffold on ${date}

## What is Turso?
Turso is SQLite at the edge — a globally distributed database built on libSQL (a fork of SQLite). It offers sub-millisecond reads from 35+ edge locations and a generous free tier (500 databases, 9GB storage).

## What was set up
| Item | Detail |
|------|--------|
| Packages | \`@libsql/client\`, \`drizzle-orm\` |
| Dev packages | \`drizzle-kit\` |
| \`lib/db.js\` | Drizzle + libSQL client |
| \`lib/schema.js\` | Example users table (SQLite dialect) |
| \`drizzle.config.js\` | Drizzle Kit configuration for Turso |

## Environment Variables
| Variable | Description | Where to get it |
|----------|-------------|-----------------|
| \`TURSO_DATABASE_URL\` | libSQL database URL | \`turso db show <name> --url\` |
| \`TURSO_AUTH_TOKEN\` | Auth token | \`turso db tokens create <name>\` |

## Turso CLI Setup
\`\`\`bash
# Install CLI
curl -sSfL https://get.tur.so/install.sh | bash

# Login
turso auth login

# Create a database
turso db create myapp

# Get URL
turso db show myapp --url

# Create auth token
turso db tokens create myapp

# Open interactive shell
turso db shell myapp
\`\`\`

## Usage

### Querying with Drizzle
\`\`\`js
import { db } from '@/lib/db';
import { users } from '@/lib/schema';
import { eq } from 'drizzle-orm';

const allUsers = await db.select().from(users);
await db.insert(users).values({ name: 'Alice', email: 'alice@example.com' });
await db.update(users).set({ name: 'Bob' }).where(eq(users.id, 1));
await db.delete(users).where(eq(users.id, 1));
\`\`\`

### Schema Management
\`\`\`bash
npx drizzle-kit push
npx drizzle-kit studio
npx drizzle-kit generate
\`\`\`

## Local Development Tip
You can point \`TURSO_DATABASE_URL\` to a local file during development:
\`\`\`
TURSO_DATABASE_URL=file:local.db
\`\`\`
No token needed for local file DBs.

## Production Checklist
- [ ] Create a production database: \`turso db create myapp --region <nearest>\`
- [ ] Set TURSO_DATABASE_URL and TURSO_AUTH_TOKEN in your hosting env
- [ ] Enable database backups: \`turso db backup\`
- [ ] For multi-region apps, enable embedded replicas

## Resources
- [Turso Docs](https://docs.turso.tech)
- [Turso + Drizzle](https://docs.turso.tech/tutorials/get-started-turso-drizzle)
- [libSQL GitHub](https://github.com/tursodatabase/libsql)
`;
}
