import { installStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Upstash Redis',
  description: 'Set up serverless Redis with Upstash — perfect for caching, rate limiting, and queues',
  category: 'Database — NoSQL',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const redisFile = hasTypescript
      ? `import { Redis } from '@upstash/redis';

// Singleton Redis client
export const redis = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL!,
  token: process.env.UPSTASH_REDIS_REST_TOKEN!,
});

// ─── Helpers ─────────────────────────────────────────────

/** Cache a value with an optional TTL in seconds */
export async function cacheSet<T>(key: string, value: T, ttlSeconds?: number): Promise<void> {
  if (ttlSeconds) {
    await redis.set(key, JSON.stringify(value), { ex: ttlSeconds });
  } else {
    await redis.set(key, JSON.stringify(value));
  }
}

/** Get a cached value (returns null on miss) */
export async function cacheGet<T>(key: string): Promise<T | null> {
  const raw = await redis.get<string>(key);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return raw as unknown as T;
  }
}

/** Delete a cached key */
export async function cacheDel(key: string): Promise<void> {
  await redis.del(key);
}
`
      : `import { Redis } from '@upstash/redis';

// Singleton Redis client
export const redis = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL,
  token: process.env.UPSTASH_REDIS_REST_TOKEN,
});

// ─── Helpers ─────────────────────────────────────────────

/** Cache a value with an optional TTL in seconds */
export async function cacheSet(key, value, ttlSeconds) {
  if (ttlSeconds) {
    await redis.set(key, JSON.stringify(value), { ex: ttlSeconds });
  } else {
    await redis.set(key, JSON.stringify(value));
  }
}

/** Get a cached value (returns null on miss) */
export async function cacheGet(key) {
  const raw = await redis.get(key);
  if (!raw) return null;
  try {
    return JSON.parse(raw);
  } catch {
    return raw;
  }
}

/** Delete a cached key */
export async function cacheDel(key) {
  await redis.del(key);
}
`;

    const rateLimiterFile = hasTypescript
      ? `import { Ratelimit } from '@upstash/ratelimit';
import { redis } from './redis';

// 10 requests per 10 seconds per identifier
export const ratelimit = new Ratelimit({
  redis,
  limiter: Ratelimit.slidingWindow(10, '10 s'),
  analytics: true,
});

export async function checkRateLimit(identifier: string) {
  const { success, limit, remaining, reset } = await ratelimit.limit(identifier);
  return { success, limit, remaining, reset };
}
`
      : `import { Ratelimit } from '@upstash/ratelimit';
import { redis } from './redis.js';

// 10 requests per 10 seconds per identifier
export const ratelimit = new Ratelimit({
  redis,
  limiter: Ratelimit.slidingWindow(10, '10 s'),
  analytics: true,
});

export async function checkRateLimit(identifier) {
  const { success, limit, remaining, reset } = await ratelimit.limit(identifier);
  return { success, limit, remaining, reset };
}
`;

    return [
      installStep(packageManager, ['@upstash/redis', '@upstash/ratelimit']),
      {
        type: 'write',
        label: `Write lib/redis.${ext}`,
        filePath: `lib/redis.${ext}`,
        content: redisFile,
      },
      {
        type: 'write',
        label: `Write lib/rate-limit.${ext}`,
        filePath: `lib/rate-limit.${ext}`,
        content: rateLimiterFile,
      },
      {
        type: 'env',
        label: 'Add Upstash env vars to .env.example',
        vars: {
          UPSTASH_REDIS_REST_URL: 'https://your-redis.upstash.io',
          UPSTASH_REDIS_REST_TOKEN: 'your-upstash-token',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/upstash-redis.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Create a free Redis database at https://console.upstash.com',
      'Copy REST URL and token into your .env file',
      'Import { redis } from "@/lib/redis" for direct Redis commands',
      'Import { cacheSet, cacheGet } from "@/lib/redis" for simple caching',
      'Import { checkRateLimit } from "@/lib/rate-limit" for rate limiting API routes',
    ];
  },
};

function docContent(date) {
  return `# Upstash Redis Setup Guide
> Generated by ai-scaffold on ${date}

## What was set up
| Item | Detail |
|------|--------|
| Packages | \`@upstash/redis\`, \`@upstash/ratelimit\` |
| \`lib/redis.js\` | Redis client + cacheSet / cacheGet / cacheDel helpers |
| \`lib/rate-limit.js\` | Sliding window rate limiter |

## Environment Variables
| Variable | Description | Where to get it |
|----------|-------------|-----------------|
| \`UPSTASH_REDIS_REST_URL\` | Redis REST endpoint | Upstash console → Database Details |
| \`UPSTASH_REDIS_REST_TOKEN\` | Redis REST token | Upstash console → Database Details |

## Usage

### Simple caching
\`\`\`js
import { cacheSet, cacheGet, cacheDel } from '@/lib/redis';

// Cache for 60 seconds
await cacheSet('user:123', { name: 'Alice' }, 60);

// Read cache
const user = await cacheGet('user:123'); // { name: 'Alice' } or null

// Invalidate cache
await cacheDel('user:123');
\`\`\`

### Direct Redis commands
\`\`\`js
import { redis } from '@/lib/redis';

await redis.set('key', 'value');
const val = await redis.get('key');
await redis.incr('page_views');
await redis.lpush('queue', 'job1');
\`\`\`

### Rate limiting API routes
\`\`\`js
// app/api/contact/route.js
import { checkRateLimit } from '@/lib/rate-limit';

export async function POST(req) {
  const ip = req.headers.get('x-forwarded-for') ?? '127.0.0.1';
  const { success } = await checkRateLimit(ip);

  if (!success) {
    return Response.json({ error: 'Too many requests' }, { status: 429 });
  }

  // ... handle request
}
\`\`\`

## Production Checklist
- [ ] Create an Upstash database at https://console.upstash.com (free tier: 10k req/day)
- [ ] Set UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN in your hosting env
- [ ] Enable Upstash eviction policy if using as a pure cache (allkeys-lru)
- [ ] Adjust rate limiter thresholds in lib/rate-limit.js for your traffic

## Resources
- [Upstash Redis Docs](https://upstash.com/docs/redis/overall/getstarted)
- [@upstash/ratelimit](https://github.com/upstash/ratelimit)
- [Upstash Console](https://console.upstash.com)
`;
}
