import { installDevStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Vitest',
  description: 'Set up Vitest for unit and integration testing — fast, ESM-native, Jest-compatible',
  category: 'Testing',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const vitestConfig = hasTypescript
      ? `import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    setupFiles: ['./tests/setup.${ext}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: ['node_modules/', 'tests/', '**/*.d.ts', '**/*.config.*'],
    },
    alias: {
      '@': path.resolve(__dirname, '.'),
    },
  },
});
`
      : `import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    setupFiles: ['./tests/setup.${ext}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: ['node_modules/', 'tests/', '**/*.config.*'],
    },
    alias: {
      '@': path.resolve(process.cwd(), '.'),
    },
  },
});
`;

    const setupFile = `// Global test setup
// import { beforeAll, afterAll } from 'vitest';

// Example: setup/teardown a test database
// beforeAll(async () => {
//   await setupTestDB();
// });
// afterAll(async () => {
//   await cleanupTestDB();
// });
`;

    const exampleTest = hasTypescript
      ? `import { describe, it, expect, vi, beforeEach } from 'vitest';

// Example unit test
describe('Math utilities', () => {
  it('adds two numbers', () => {
    expect(1 + 1).toBe(2);
  });

  it('handles edge cases', () => {
    expect(Number.isNaN(NaN)).toBe(true);
    expect(0.1 + 0.2).toBeCloseTo(0.3);
  });
});

// Example with mocks
describe('Service with mocked dependency', () => {
  const mockFetch = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
    global.fetch = mockFetch;
  });

  it('fetches and returns data', async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: async () => ({ id: 1, name: 'Alice' }),
    });

    const res = await fetch('/api/user/1');
    const data = await res.json();

    expect(mockFetch).toHaveBeenCalledWith('/api/user/1');
    expect(data.name).toBe('Alice');
  });
});
`
      : `import { describe, it, expect, vi, beforeEach } from 'vitest';

describe('Math utilities', () => {
  it('adds two numbers', () => {
    expect(1 + 1).toBe(2);
  });

  it('handles edge cases', () => {
    expect(Number.isNaN(NaN)).toBe(true);
    expect(0.1 + 0.2).toBeCloseTo(0.3);
  });
});

describe('Service with mocked dependency', () => {
  const mockFetch = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
    global.fetch = mockFetch;
  });

  it('fetches and returns data', async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: async () => ({ id: 1, name: 'Alice' }),
    });

    const res = await fetch('/api/user/1');
    const data = await res.json();

    expect(mockFetch).toHaveBeenCalledWith('/api/user/1');
    expect(data.name).toBe('Alice');
  });
});
`;

    return [
      installDevStep(packageManager, ['vitest', '@vitest/coverage-v8'], 'Install vitest + coverage (dev)'),
      {
        type: 'write',
        label: `Write vitest.config.${ext}`,
        filePath: `vitest.config.${ext}`,
        content: vitestConfig,
      },
      {
        type: 'write',
        label: `Write tests/setup.${ext}`,
        filePath: `tests/setup.${ext}`,
        content: setupFile,
      },
      {
        type: 'write',
        label: `Write tests/example.test.${ext}`,
        filePath: `tests/example.test.${ext}`,
        content: exampleTest,
      },
      {
        type: 'doc',
        label: 'Write docs/vitest.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Run tests: `npx vitest`',
      'Run once: `npx vitest run`',
      'Run with coverage: `npx vitest run --coverage`',
      'Add "test": "vitest" and "test:coverage": "vitest run --coverage" to package.json scripts',
      'Write tests in tests/**/*.test.js or co-located as *.test.js alongside source files',
    ];
  },
};

function docContent(date) {
  return `# Vitest Setup Guide
> Generated by ai-scaffold on ${date}

## What was set up
| Item | Detail |
|------|--------|
| Dev packages | \`vitest\`, \`@vitest/coverage-v8\` |
| \`vitest.config.js\` | Vitest config with coverage and path aliases |
| \`tests/setup.js\` | Global test setup file |
| \`tests/example.test.js\` | Example tests with mocks |

## Commands
\`\`\`bash
npx vitest             # watch mode
npx vitest run         # run once (CI)
npx vitest run --coverage  # with coverage report
npx vitest ui          # visual UI (install @vitest/ui first)
\`\`\`

## Writing Tests
\`\`\`js
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

describe('MyService', () => {
  it('does something', () => {
    expect(myFn(1, 2)).toBe(3);
  });

  it('handles async', async () => {
    const result = await fetchUser(1);
    expect(result).toMatchObject({ id: 1 });
  });

  it('mocks a module', async () => {
    vi.mock('@/lib/db', () => ({ db: { select: vi.fn().mockResolvedValue([]) } }));
    // ...
  });
});
\`\`\`

## Resources
- [Vitest Docs](https://vitest.dev)
- [Vitest API](https://vitest.dev/api)
`;
}
