import { installStep, installDevStep } from './utils.js';

const DATE = new Date().toISOString().split('T')[0];

export default {
  name: 'Xata',
  description: 'Set up Xata — serverless Postgres with built-in full-text search, branching, and typed SDK',
  category: 'Database — SQL (Managed Cloud)',
  supportedFrameworks: [],

  steps(context) {
    const { hasTypescript, packageManager } = context;
    const ext = hasTypescript ? 'ts' : 'js';

    const xataClient = hasTypescript
      ? `// Generated by Xata CLI: xata codegen
// Run: npx @xata.io/cli@latest codegen --output src/xata.ts

// Manual client setup (if not using codegen):
import { XataClient } from '@xata.io/client';

let instance: XataClient | undefined;

export function getXataClient(): XataClient {
  if (instance) return instance;

  instance = new XataClient({
    apiKey: process.env.XATA_API_KEY!,
    databaseURL: process.env.XATA_DATABASE_URL!,
    branch: process.env.XATA_BRANCH ?? 'main',
  });

  return instance;
}

export const xata = getXataClient();
`
      : `import { XataClient } from '@xata.io/client';

let instance;

export function getXataClient() {
  if (instance) return instance;
  instance = new XataClient({
    apiKey: process.env.XATA_API_KEY,
    databaseURL: process.env.XATA_DATABASE_URL,
    branch: process.env.XATA_BRANCH ?? 'main',
  });
  return instance;
}

export const xata = getXataClient();
`;

    const usageExample = hasTypescript
      ? `// Example usage with Xata's TypeScript SDK
// Run 'npx @xata.io/cli@latest codegen' to get a fully-typed client

import { xata } from './xata';

// ─── CRUD ────────────────────────────────────────────────

// Create a record
const user = await xata.db.users.create({ name: 'Alice', email: 'alice@example.com' });

// Read a record
const found = await xata.db.users.read('rec_xxx');

// Update a record
await xata.db.users.update('rec_xxx', { name: 'Alice Smith' });

// Delete a record
await xata.db.users.delete('rec_xxx');

// ─── Queries ─────────────────────────────────────────────

// Filter
const admins = await xata.db.users.filter('role', 'admin').getMany();

// Sort
const recent = await xata.db.users.sort('xata.createdAt', 'desc').getFirst();

// Pagination
const page = await xata.db.users.getPaginated({ pagination: { size: 20, after: cursor } });

// ─── Full-text search (built-in!) ─────────────────────────

const results = await xata.db.posts.search('typescript tutorial', {
  fuzziness: 1,
  target: ['title', 'content'],
});
`
      : `import { xata } from './xata.js';

// Create
const user = await xata.db.users.create({ name: 'Alice', email: 'alice@example.com' });

// Read
const found = await xata.db.users.read('rec_xxx');

// Update
await xata.db.users.update('rec_xxx', { name: 'Alice Smith' });

// Delete
await xata.db.users.delete('rec_xxx');

// Filter + sort
const recent = await xata.db.users.sort('xata.createdAt', 'desc').getFirst();

// Search (built-in full-text)
const results = await xata.db.posts.search('typescript tutorial');
`;

    return [
      installStep(packageManager, ['@xata.io/client']),
      installDevStep(packageManager, ['@xata.io/cli'], 'Install @xata.io/cli (dev)'),
      {
        type: 'write',
        label: `Write lib/xata.${ext}`,
        filePath: `lib/xata.${ext}`,
        content: xataClient,
      },
      {
        type: 'write',
        label: `Write lib/xata-example.${ext}`,
        filePath: `lib/xata-example.${ext}`,
        content: usageExample,
      },
      {
        type: 'env',
        label: 'Add Xata env vars to .env.example',
        vars: {
          XATA_API_KEY: 'xau_your-xata-api-key',
          XATA_DATABASE_URL: 'https://your-workspace.xata.sh/db/your-database',
          XATA_BRANCH: 'main',
        },
      },
      {
        type: 'doc',
        label: 'Write docs/xata.md',
        content: docContent(DATE),
      },
    ];
  },

  nextSteps() {
    return [
      'Create a free account at https://xata.io',
      'Create a workspace and database in the Xata dashboard',
      'Run `npx @xata.io/cli@latest auth login` to authenticate',
      'Run `npx @xata.io/cli@latest init` in your project to link it',
      'Run `npx @xata.io/cli@latest codegen` to generate a typed client',
      'Use xata.db.yourTable.create/read/update/delete/search for typed queries',
    ];
  },
};

function docContent(date) {
  return `# Xata Setup Guide
> Generated by ai-scaffold on ${date}

## What is Xata?
Xata is a serverless Postgres platform with a friendly TypeScript SDK, database branching (like git), built-in full-text search, and zero-config setup.

## What was set up
| Item | Detail |
|------|--------|
| Package | \`@xata.io/client\` |
| Dev package | \`@xata.io/cli\` |
| \`lib/xata.js\` | Xata client singleton |
| \`lib/xata-example.js\` | CRUD + search usage examples |

## Quick Start
\`\`\`bash
# Authenticate
npx @xata.io/cli@latest auth login

# Link your project (creates .xatarc)
npx @xata.io/cli@latest init

# Generate typed client
npx @xata.io/cli@latest codegen --output lib/xata.ts
\`\`\`

## Resources
- [Xata Docs](https://xata.io/docs)
- [TypeScript SDK](https://xata.io/docs/sdk/typescript/overview)
- [Xata Search](https://xata.io/docs/sdk/search)
`;
}
